name: Gym Scraper
on:
  schedule:
    - cron: '*/20 * * * *'
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - env:
          DENSITY_TOKEN: ${{ secrets.DENSITY_TOKEN }}
        run: python RSF_Scraper.py
        
      - run: python make_graph.py
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update: $(date)" || exit 0
          git push
